ChinukMaster/ChinukMaster/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('billing.urls')),
    path('prappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChinukMaster/billing/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search_result, name='search_result'),

    path('show/<slug:obj>', views.show_objects, name='show_objects'),
    path('show/payments/<slug:obj>', views.show_payments, name='show_payments'),
    path('<slug:obj>/<int:id>', views.detail_object, name='detail_object'),

    path('edit/<slug:obj>/<int:id>', views.edit_object, name='edit_object'),

    path('delete/<slug:obj>/<int:id>', views.delete_object, name='delete_object'),
    path('delete/duplicated/<slug:obj>/<int:id>', views.delete_duplicated, name='delete_duplicated'),

    path('new/<slug:obj>', views.new_object, name='new_object'),

    path('<slug:obj>/<int:id>/payments/history', views.payments_history, name='payments_history'),

    path('report', views.get_report, name='get_report'),
]

ChinukMaster/billing/models.py
from django.db import models
from django.utils import timezone
from datetime import date

class Trener(models.Model):
    name = models.CharField(max_length=50, verbose_name = 'Имя')
    tel_number = models.CharField(max_length=20, verbose_name = 'Номер телефона', null=True, blank=True)
    info = models.TextField(blank=True, null=False, verbose_name = 'Дополнительная информация')
    photo = models.ImageField(verbose_name='Фото', upload_to='billing/media/treners', height_field=None, width_field=None, null=True, blank=True)

    class Meta:
        verbose_name = 'Тренер'
        verbose_name_plural = 'Тренеры'

    def __str__(self):
        return self.name

    def last_name(self):
        return self.name.split(" ")[0]

    @staticmethod
    def total_count():
        return Trener.objects.all().count()


class Group(models.Model):

    gr_type_choices = [
        ('A', 'Взрослая'),
        ('C', 'Детская')
    ]

    sport_type_choices = [
        ('B', 'Классический бокс'),
        ('T', 'Тайский бокс'),
        ('W', 'Женская группа'),
        ('M', 'ММА')
    ]

    schedule_choice = [
        ('uneven', 'пн. ср. пт.'),
        ('even', 'вт. чт. сб.'),
    ]

    gr_type = models.CharField(verbose_name='Возраст', max_length=1, choices=gr_type_choices, default='A')
    sport_type = models.CharField(verbose_name='Тип', max_length=1, choices = sport_type_choices, default='T')
    time = models.TimeField(verbose_name='Время')
    schedule = models.CharField(verbose_name='Расписание', max_length=6, choices=schedule_choice, null=True, blank=True)
    trener = models.ForeignKey('Trener', verbose_name='Тренер', on_delete=models.SET_NULL, null=True, blank=True)
    address = models.ForeignKey('Address', verbose_name='Зал', on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        ordering = ['trener']

    def __str__(self):
        return f'{self.trener} {self.schedule} {self.time}'

    def clients_amount(self):
        clients = self.client_set.all()
        return len(clients)

    @staticmethod
    def total_count():
        return Group.objects.all().count()

class Client(models.Model):
    member_card = models.CharField(verbose_name='Членская карта', max_length=4, blank=True, null=True)
    name = models.CharField(verbose_name='ФИО', max_length=50, blank=True, null=True)
    tel_number = models.CharField(verbose_name='Номер телефона', max_length=20, blank=True, null=True)
    info = models.TextField(verbose_name='Дополнительная информация', null=True, blank=True)
    training_type_choices = [
        ('I', 'Индивидуал'),
        ('G', 'В группе'),
        ('B', 'Смешанный'),
    ]
    cl_type = models.CharField(verbose_name='Тип клиента', max_length=1, choices=training_type_choices, default='G')
    treners = models.ManyToManyField(Trener, verbose_name='Тренер', blank=True)
    groups = models.ManyToManyField(Group, verbose_name='Группа', blank=True)

    def __str__(self):
        if self.member_card:
            return f'{self.member_card} : {self.name}'
        return self.name

    def last_payment(self):
        payments = self.payment_set.order_by('-date')
        if payments:
            return payments[0]

    @staticmethod
    def total_count():
        return Client.objects.all().count()
        
         
    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ['name']


class Address(models.Model):

    address_choices = [
        ('Машерова 17/4', 'Машерова 17/4'),
        ('Свердлова 23', 'Свердлова 23')
    ]

    address = models.CharField(max_length=20, choices = address_choices)
    tel_number = models.CharField(max_length = 20)

    class Meta:
        verbose_name = 'Адрес'
        verbose_name_plural = 'Адреса'

    def __str__(self):
        return self.address

class Payment(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='Плательщик', null=True)

    payment_to_choices = [
        ('G', 'В группу'),
        ('I', 'Индивидуально')
    ]
    payment_type_choices = [
        ('O', 'Разовый платеж'),
        ('M', 'Месячный взнос')
    ]

    payment_to = models.CharField(max_length=1, choices=payment_to_choices, default='G', verbose_name='Направление оплаты')
    payment_type = models.CharField(max_length=1, choices=payment_type_choices, default='M', verbose_name='Тип оплаты')
    trener = models.ForeignKey(Trener, on_delete=models.SET_NULL, verbose_name='Тренер', blank=True, null=True)
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, verbose_name='Группа', blank=True, null=True)
    date = models.DateField(verbose_name='Дата оплаты', default=timezone.now)
    amount = models.FloatField(verbose_name='Сумма', default=60)
    trener_part = models.FloatField(verbose_name='Тренеру', default=0)

    def today(self):
        return date.today()

    def total_amount(self):
        return self.amount - self.trener_part

    def __str__(self):
        return f'{self.date}: {self.amount} BYN'

    class Meta:
        verbose_name = 'Оплата'
        verbose_name_plural = 'Оплаты'
        ordering = ['-date']

ChinukMaster/billing/forms.py
from django import forms
from .models import *

class ClientForm(forms.ModelForm):
    
    class Meta:
        model = Client
        fields = '__all__'

class PaymentForm(forms.ModelForm):

    class Meta:
        model = Payment
        fields = '__all__'

class TrenerForm(forms.ModelForm):

    class Meta:
        model = Trener
        fields = '__all__'

class GroupForm(forms.ModelForm):

    class Meta:
        model = Group
        fields = '__all__'

class AddressForm(forms.ModelForm):

    class Meta:
        model = Address
        fields = '__all__'

ChinukMaster/billing/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.http import HttpResponse, Http404
from django.utils import timezone
from .models import *
from .forms import *
from datetime import date, timedelta

# Global varibles

obj_values = {
    'trener' : Trener, 
    'client' : Client,
    'group'  : Group,
    'payment': Payment,
    'address': Address,
    }

obj_forms = {
    'trener' : TrenerForm, 
    'client' : ClientForm,
    'group'  : GroupForm,
    'payment': PaymentForm,
    'address': AddressForm,
}

# Functions-supporters

def get_obj_link(obj):
    for k, v in obj_values.items():
        if v == type(obj):
            obj_link = k
    return obj_link

def total_payment(payments, date=date.today()):
    result = 0
    for payment in payments:
        if payment.date >= date:
            result += payment.total_amount()

    return result

# Views

def index(request):

    return render(request, 'billing/index.html', {
        'trener_model' : Trener, 
        'client_model' : Client,
        'group_model'  : Group,
    })

def search_result(request):

    models = [Client, Trener, Group, Address, Payment]

    if request.method == 'POST':
        search_request = request.POST['search_request']
        query_sets = []

        for model in models:
            if model == Trener or model == Client:
                if search_request.isdigit():
                    if model == Client:
                        objs = model.objects.filter(member_card__contains=f'{search_request}')
                        if objs:
                            query_sets.append(objs)
                    objs = model.objects.filter(tel_number__contains=f'{search_request}')
                    if objs:
                        query_sets.append(objs)
                else:
                    objs = model.objects.filter(name__contains=f'{search_request}')
                    if objs:
                        query_sets.append(objs)

        if query_sets:
            if len(query_sets) == 1:
                objs_set = query_sets[0]
                if len(objs_set) == 1:
                    obj = objs_set[0]
                    obj_link = get_obj_link(obj)
                    return redirect('detail_object', obj=obj_link, id=obj.id)
            obj_pairs = {}
            for query_set in query_sets:
                for obj in query_set:
                    obj_link = get_obj_link(obj)
                    obj_pairs[obj] = obj_link
            return render(request, 'billing/search_result.html', {
                'obj_pairs' : obj_pairs,
            })

            return HttpResponse(query_sets)

        return HttpResponse('Nothing')


def show_objects(request, obj):

    inst = obj_values[obj].objects.all()

    paginator = Paginator(inst, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    show_obj_link = f'{obj}s' if obj != 'address' else f'{obj}es'

    return render(request, f'billing/show/{show_obj_link}.html', {
        f'{show_obj_link}' : inst,
        'page_obj' : page_obj,
    })

def show_payments(request, obj):
    payments = Payment.objects.all()

    payments_group = Payment.objects.filter(payment_to='G')
    payments_individuals = Payment.objects.filter(payment_to='I')

    if obj == 'groups':
        paginator = Paginator(payments_group, 20)
    elif obj == 'individuals':
        paginator = Paginator(payments_individuals, 20)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'billing/show/payments.html', {
        'payment_type' : obj,
        'page_obj' : page_obj, 

    })

def detail_object(request, obj, id):
    model = obj_values[obj]
    inst = obj_values[obj].objects.get(id=id)
    page_obj = ''

    if obj == 'group':
        clients = inst.client_set.all()
        paginator = Paginator(clients, 50)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

    return render(request, f'billing/detail/{obj}.html', {
        f'{obj}_model' : model,
        f'{obj}' : inst,
        'page_obj' : page_obj,
    })

def new_object(request, obj):
    form = obj_forms[obj]

    if request.method == 'POST':
        form = form(request.POST)
        if form.is_valid():
            inst = form.save()
            return redirect('detail_object', obj, inst.id)
    else:
        return render(request, 'billing/object_form.html', {
            'obj' : obj,
            'form' : form,
        })

def edit_object(request, obj, id):
    inst = obj_values[obj].objects.get(id=id)

    if request.method == 'POST':
        form = obj_forms[obj](request.POST, instance=inst)
        if form.is_valid():
            inst = form.save()
            return redirect('detail_object', obj, inst.id)
    else:
        form = obj_forms[obj](instance=inst)
        return render(request, 'billing/object_form.html', {
            'obj' : inst,
            'form' : form,
        })

def delete_object(request, obj, id):
    inst = obj_values[obj].objects.get(id=id)
    inst.delete()

    show_obj_link = f'{obj}s' if obj != 'address' else f'{obj}es'

    return redirect('show_objects', obj)

def delete_duplicated(request, obj, id):
    inst = obj_values[obj].objects.get(id=id)
    
    if obj == 'group':
        clients = inst.client_set.all()

        for client in clients:
            if (inst.client_set.filter(name=client.name).count() > 1 and 
                    inst.client_set.filter(member_card=client.member_card).count() > 1):
                client.delete()

    return redirect('show_objects', obj)    
    

def payments_history(request, obj, id):
    inst = obj_values[obj].objects.get(id=id)

    payments = inst.payment_set.all()

    paginator = Paginator(payments, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'billing/payments_history.html', {
        'inst' : inst,
        'page_obj' : page_obj,
    })

def get_report(request):
    payments = Payment.objects.all()
    return render(request, 'billing/report.html', {
        'payments': payments,
        'total_payment' : total_payment(payments, date.today()),
    })

ChinukMaster/ChinukMaster/templates/billing/detail/client.html
{% extends 'billing/base.html' %}

{% block title %}{{client.name}}{% endblock %}

{% block content %}

    <div class="container-xxl">
        <div class="row">
            <div class="col-4">
                <div class="detail-photo d-flex justify-content-center">
                    {% if client.photo %}
                        <img src="{{trener.photo.url}}" alt="{{trener.name}}" class="rounded w-50 h-50">
                    {% else %}
                        <img src="/media/billing/media/unknown.png" alt="unknown user" class="rounded w-50 h-50">
                    {% endif %}
                </div>
            </div>
            <div class="col-8">
                <div class="row mb-3">
                    <div class="col">
                        <a href="{% url 'edit_object' obj='client' id=client.id %}" class="btn btn-warning p-3 w-100 rounded shadow">
                            Изменить
                        </a>
                    </div>
                    <div class="col">
                        <a href="{% url 'delete_object' obj='client' id=client.id %}" class="btn btn-danger p-3 w-100 rounded shadow">Удалить</a>  
                    </div>
                </div>
                <div class="row text-center">
                    {% if client.member_card %}
                        <div class="col-3">
                            <h4 class="p-3 shadow rounded">{{ client.member_card }}</h4>
                        </div>
                    {% endif %}
                    <div class="col">
                        <h4 class="p-3 shadow rounded">{{ client.name }}</h4>
                    </div>
                </div>
                <div class="row text-center">
                    {% if client.tel_number %}
                        <div class="col-6">
                            <p class="p-3 shadow rounded">{{ client.tel_number }}</p>
                        </div>
                    {% endif %}
                    <div class="col">
                        <p class="p-3 shadow rounded">Тип клиента: 
                            {% if client.cl_type == 'I' %} Индивидуал
                            {% elif client.cl_type == 'G' %} В группе
                            {% elif client.cl_type == 'B' %} Смешанный
                            {% endif %}
                        </p>
                    </div>
                </div>
                <div class="row">
                    {% if client.info %}
                        <div class="col">
                            <p class="p-3 shadow rounded">{{client.info}}</p>
                        </div>
                    {% endif %}
                </div>
                {% if client.last_payment %}
                    <div class="row mb-3">
                        <div class="col-8">
                            <a href="{% url 'detail_object' 'payment' client.last_payment.id %}" class="p-3 shadow rounded w-100 btn btn-info">
                                Последняя оплата: {{client.last_payment.date}} | {{client.last_payment.amount}} BYN
                            </a>
                        </div>
                        <div class="col-4">
                            <a href="{% url 'payments_history' 'client' client.id %}" class="btn btn-info p-3 rounded shadow w-100">
                                История оплат
                            </a>
                        </div>
                    </div>
                {% endif %}
                <div class="row">
                    {% if client.groups.all %}
                        <div class="col">
                            <p class="shadow rounded p-3 text-center">Группы: </p>
                            {% for group in client.groups.all %}
                                <p><a href="{% url 'detail_object' 'group' group.id %}" class="p-3 rounded shadow btn btn-info w-100">
                                    {{ group.trener.name }}, {{ group.time }}, 
                                    {% if group.schedule == 'uneven' %} пн. ср. пт. 
                                    {% else %} вт. чт. сб.
                                    {% endif %} 
                                </a></p>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if client.treners.all %}
                        <div class="col">
                            <p class="shadow rounded p-3 text-center">Тренеры: </p>
                            {% for trener in client.treners.all %}
                                <p><a href="{% url 'detail_object' 'trener' trener.id %}" class="p-3 rounded shadow btn btn-info w-100">
                                    {{ trener.name }}
                                </a></p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

ChinukMaster/ChinukMaster/templates/billing/detail/group.html
{% extends 'billing/base.html' %}

{% block title %}{{group.trener.last_name}}, {{group.time}}{% endblock %}

{% block content %}
    <div class="container-xxl d-flex flex-column align-items-center">
        <div class="row text-center mb-4 w-50">
            <a href="{% url 'detail_object' 'trener' group.trener.id %}" class="btn btn-info col p-4 shadow rounded m-2">{{group.trener}}</a>
        </div>
    </div>
    <div class="row mb-4 text-center">
        <div class="col p-4 shadow rounded m-2">
            Тип занятий: 
            {% if group.sport_type == 'B' %} Классический бокс
            {% elif group.sport_type == 'T' %} Тайский бокс
            {% elif group.sport_type == 'W' %} Женская группа
            {% elif group.sport_type == 'M' %} ММА
            {% endif %}
        </div>
        <div class="col p-4 shadow rounded m-2">
            Тип группы:
            {% if group.gr_type == 'A' %} Взрослая
            {% else %} Детская
            {% endif %}
        </div>
        <div class="col p-4 shadow rounded m-2">
            Расписание:
            {% if group.schedule == 'even' %} вт. чт. сб.
            {% else %} пн. ср. пт. 
            {% endif %}
        </div>
        <div class="col p-4 shadow rounded m-2">Время: {{group.time}}</div>
    </div>
    <div class="container-xxl d-flex flex-column align-items-end">
        <div class="row text-center mb-4 w-50">
            <div class="col-6 p-4 shadow rounded m-2">
                Адрес: {{group.address}}
            </div>
            <a href="{% url 'delete_duplicated' 'group' group.id %}" class="btn btn-warning col p-4 shadow rounded m-2">
                Очитстить повторы
            </a>
            <a href="{% url 'delete_object' 'group' group.id %}" class="btn btn-danger col p-4 shadow rounded m-2">
                Удалить группу
            </a>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-4">
        <table class="table table-hover w-75">
            <thead>
                <tr class="text-center">
                    <th scope="col" colspan="5">Клиенты в группе</th>
                </tr>
                <tr class="text-center">
                    <th scope="col">Карточка</th>
                    <th scope="col">ФИО</th>
                    <th scope="col">Телефон</th>
                    <th scope="col">Последняя оплата</th>
                    <th scope="col">Сумма</th>
                </tr>
            </thead>
            <tbody>
                {% for client in page_obj %}
                    <tr class="text-center">
                        <td><a class="link" href="{% url 'detail_object' obj='client' id=client.id %}">{{client.member_card}}</a></td>
                        <td><a class="link" href="{% url 'detail_object' obj='client' id=client.id %}">{{client.name}}</a></td>
                        <td>{{client.tel_number}}</td>
                        <td>{{client.last_payment.date}}</td>
                        <td>{{client.last_payment.total_amount}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

ChinukMaster/ChinukMaster/templates/billing/detail/payment.html
{% extends 'billing/base.html' %}

{% block title %}PAYMENT{% endblock %}

{% block content %} 

    <p>Дата оплаты: {{payment.date}}</p>
    <p>Клиент: <a href="{% url 'detail_object' 'client' payment.client.id %}">{{payment.client}}</a></p>
    <p>Тип оплаты: 
        {% if payment.payment_type == 'O' %}
            Разовый
        {% else %}
            За месяц
        {% endif %}
    </p>
    <p>Направление оплаты: 
        {% if payment.payment_to == 'G' %}
            В группу
            <p>
                Группа: {{payment.group}}
            </p>
        {% else %}
            Индивидуально
            <p>
                Тренер: {{payment.trener}}
            </p>
        {% endif %}
    </p>
    <p>Сумма: {{payment.amount}} / {{payment.trener_part}}</p>
    <p>Приход: {{payment.total_amount}}</p>

{% endblock %}

ChinukMaster/ChinukMaster/templates/billing/detail/trener.html
{% extends 'billing/base.html' %}

{% block title %}{{trener.name}}{% endblock %}

{% block content %}

    <div class="container-xxl">
        <div class="row">
            <div class="col-5">
                <div class="row h-50">
                    {% if trener.photo %}
                        <div class="detail-photo d-flex justify-content-center">
                            <img src="{{trener.photo.url}}" alt="{{trener.name}}" class="rounded">
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-7">
                <div class="row h-100">
                    <div class="col text-center">
                        <div class="row mb-3">
                            <div class="col">
                                <a href="{% url 'edit_object' 'trener' trener.id %}" class="btn btn-warning p-4 w-100 shadow rounded">Изменить</a>
                            </div>
                            <div class="col">
                                <a href="{% url 'delete_object' 'trener' trener.id %}" class="btn btn-danger p-4 w-100 shadow rounded">Удалить</a>
                            </div>
                        </div>
                        <div class="row">
                            <h5 class="p-4 rounded shadow">{{ trener.name }}</h5>
                        </div>
                        {% if trener.info %}
                            <div class="row">
                                <p class="p-4 rounded shadow">{{ trener.info}}</p>
                            </div>
                        {% endif %}
                        <div class="row">
                            <p class="p-4 rounded shadow">{{ trener.tel_number }}</p>
                        </div>
                        <div class="row">
                            {% if trener.group_set.all %}
                                <div class="col-6">
                                    <p class="p-4 rounded shadow">Группы:</p> 
                                    {% for group in trener.group_set.all %}
                                        <p><a class="btn btn-info p-4 shadow rounded w-100" href="{% url 'detail_object' 'group' group.id %}">
                                            {{ group.time }}, 
                                            {% if group.schedule == 'uneven' %}
                                                пн. ср. пт. {% else %} вт. чт. сб. 
                                            {% endif %} 
                                        </a></p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                            {% if trener.client_set.all %}
                                <div class="col-6">
                                    <p class="p-4 rounded shadow">Индивидуалы: </p>
                                    {% for individual in trener.client_set.all %}
                                        <p><a class="btn btn-info p-4 shadow rounded w-100" href="{% url 'detail_object' 'client' individual.id %}">
                                            {{ individual }}
                                        </a></p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}